version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --no-bin-links
      - run:
          name: where my node modules
          command: ls
      - run:
          name: Ensure game builds
          command: make game.p8
